export const NAV_TYPES = {
    LOGIN : "LOGIN",
    HOMELIST : "HOMELIST",
    CHATPERSON:"CHATPERSON",
    CHATPERSON_MAIN:"CHATPERSON_MAIN",
    PROFILE:"PROFILE",
    NEWFEED:'NEWFEED',
    SCAN:"SCAN",
    CONTACT:"CONTACT",
    CREATEGROUP:"CREATEGROUP",


    
    INTRO: "INTRO",
    CORE: "CORE",
    START_UP: "START_UP",
    MAIN: "MAIN",
    MAIN_HOME: "MAIN_HOME"
};